version: "3.8"

services:
    mysql:
        image: mysql:8.0.21
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            GHOST_DATABASE: ${GHOST_DATABASE}
            YOURLS_DATABASE: ${YOURLS_DATABASE}
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    postgres:
        image: postgres:12.4-alpine
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
    nginx:
        image: nginx:1.19.2-alpine
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - ghost
            - yourls
        environment:
            GHOST_HOST: ${GHOST_HOST}
            GHOST_PORT: ${GHOST_PORT}
            YOURLS_HOST: ${YOURLS_HOST}
            YOURLS_PORT: ${YOURLS_PORT}
        volumes:
            - ./nginx/templates:/etc/nginx/templates
            - yourls:/var/www/html
    ghost:
        image: ghost:3.31.5-alpine
        restart: always
        depends_on:
            - mysql
        environment:
            database__client: mysql
            database__connection__host: mysql
            database__connection__user: ${MYSQL_USER}
            database__connection__password: ${MYSQL_PASSWORD}
            database__connection__database: ${GHOST_DATABASE}
            url: http://${GHOST_HOST}
    yourls:
        image: yourls:1.7.9-fpm-alpine
        restart: always
        depends_on:
            - mysql
        environment:
            YOURLS_DB_HOST: mysql
            YOURLS_DB_USER: ${MYSQL_USER}
            YOURLS_DB_PASS: ${MYSQL_PASSWORD}
            YOURLS_DB_NAME: ${YOURLS_DATABASE}
            YOURLS_SITE: http://${YOURLS_HOST}
            YOURLS_USER: ${YOURLS_USER}
            YOURLS_PASS: ${YOURLS_PASS}
        volumes:
            - yourls:/var/www/html
    redbot:
        restart: always
        image: docker.pkg.github.com/park9eon/red-discordbot-docker/redbot:latest
        depends_on:
            - postgres
        environment:
            REDBOT_NAME: redbot
            REDBOT_STORAGE_TYPE: POSTGRES
            REDBOT_TOKEN: ${REDBOT_TOKEN}
            REDBOT_PREFIX: "!"
            REDBOT_DB_HOST: postgres
            REDBOT_DB_USER: ${POSTGRES_USER}
            REDBOT_DB_PASS: ${POSTGRES_PASSWORD}
            REDBOT_DB_NAME: ${POSTGRES_DB}

volumes:
    yourls: