#!/usr/bin/env bash

mysql -u root -p${MYSQL_ROOT_PASSWORD} <<< "

CREATE DATABASE IF NOT EXISTS \`${GHOST_DATABASE}\`;
CREATE DATABASE IF NOT EXISTS \`${YOURLS_DATABASE}\`;

GRANT ALL ON \`${GHOST_DATABASE}\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL ON \`${YOURLS_DATABASE}\`.* TO '${MYSQL_USER}'@'%';

"